application: panwachrome
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/upload/.*
  script: panwachrome.app
  login: admin

- url: /upload
  script: panwachrome.app
  login: admin

- url: /uploadform.html
  script: panwachrome.app
  login: admin

- url: /.*
  script: panwachrome.app